<a href="https://colab.research.google.com/github/geethikad/Assignment1/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### Assessment

###### I am going to provide two .csv files , you are supposed to work on them and have to provide solutions to the following problems

###### import necessary libraries

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

###### merge those two csv files (after getting as dataframes, get them as a single dataframe)

In [12]:
df = pd.concat(
    map(pd.read_csv, ['/content/college_1.csv', '/content/college_2.csv']), ignore_index=True)
print(df)

              Name  python  mysql  Previous Geekions  CodeKata Score  \
0        A.Dharani    82.0   20.0              24500           24500
1      V.JEEVITHA     82.0   20.0              21740           21740
2      HEMAVATHI.R   100.0  100.0              19680           19680
3      Mugunthan S   100.0   47.0              10610           10610
4      Sathammai.S   100.0    8.0               8980            8980
..             ...     ...    ...                ...             ...
114  praveen raj j    24.0    0.0               2380            2380
115     AMARNATH D    -1.0   12.0               1890            1890
116           bala    32.0    0.0               1720            1720
117           XY Z    -1.0   -1.0                  0               0
118      Hariharan    -1.0   -1.0                  0               0

                                    Department  Rising  python_en  \
0             Computer Science and Engineering       0        NaN
1             Computer Science and Engineering       0        NaN
2             Computer Science and Engineering       0        NaN
3             Computer Science and Engineering       0        NaN
4             Computer Science and Engineering       0        NaN
..                                         ...     ...        ...
114           Computer Science and Engineering       0       -1.0
115  Electronics and Communication Engineering       0       52.0
116  Electronics and Communication Engineering       0       49.0
117           Computer Science and Engineering       0       20.0
118           Computer Science and Engineering       0       -1.0

     computational_thinking
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
..                      ...
114                     0.0
115                    -1.0
116                    -1.0
117                    -1.0
118                     0.0

[119 rows x 9 columns]

###### Take each csv file , split that csv file into multiple categories (example csv files are added in the repo)

###### consider if the codekata score exceeds 15000 points(present week) then make a csv on those observations as Exceeded expectations.csv

In [34]:
exceeded_expectation = df[df['CodeKata Score']>15000]
exceeded_expectation.reset_index(drop=True)

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,A.Dharani,82.0,20.0,24500,24500,Computer Science and Engineering,0,NaN,NaN
1,V.JEEVITHA,82.0,20.0,21740,21740,Computer Science and Engineering,0,NaN,NaN
2,HEMAVATHI.R,100.0,100.0,19680,19680,Computer Science and Engineering,0,NaN,NaN
3,ASHOK KUMAR K,100.0,31.0,19400,19400,Electronics and Electrical Engineering,0,0.0,9.0

In [35]:
exceeded_expectation.to_csv("/content/Exceeded_expectations.csv",index=False)

###### if  10000<codekata score<15000   (Reached_expectations.csv)

In [33]:
reached_expectation = df[(df['CodeKata Score']>10000) & (df['CodeKata Score']<15000)]
reached_expectation.reset_index(drop=True)

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,Mugunthan S,100.0,47.0,10610,10610,Computer Science and Engineering,0,NaN,NaN
1,Chandru,0.0,0.0,14150,14490,Computer Science and Engineering,340,20.0,0.0
2,Ganesh Ramkumar R,-1.0,24.0,8790,10790,Computer Science and Engineering,2000,55.0,6.0
3,Bodipudi Harini,-1.0,35.0,10040,10040,Electronics and Communication Engineering,0,0.0,-1.0

In [32]:
reached_expectation.to_csv("/content/Reached_Expectation.csv",index=False)

###### if  7000<codekata score<10000   (Needs_Improvement.csv)

In [30]:
Needs_Improvements = df[(df['CodeKata Score']>7000) & (df['CodeKata Score']<10000)]
Needs_Improvements.reset_index(drop=True)

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,Sathammai.S,100.0,8.0,8980,8980,Computer Science and Engineering,0,NaN,NaN
1,NIVEESHWAR S,100.0,0.0,8200,8200,Computer Science and Engineering,0,NaN,NaN
2,KALAIARASAN K,85.0,47.0,7750,7880,Electronics and Communication Engineering,130,NaN,NaN
3,MOHAMED ZUBAIR AHMED,82.0,4.0,7020,7020,Computer Science and Engineering,0,NaN,NaN
4,VIINU V P,-1.0,24.0,9150,9150,Electronics and Electrical Engineering,0,100.0,-1.0
5,Poojitha Y,0.0,35.0,7210,8970,Computer Science and Engineering,1760,78.0,0.0
6,Gowtham Chandrasekaran,-1.0,0.0,7250,8950,Computer Science and Engineering,1700,0.0,3.0
7,Gowtham R,-1.0,4.0,8650,8650,Electronics and Communication Engineering,0,60.0,6.0
8,shifak N,58.0,0.0,5180,8320,Electronics and Electrical Engineering,3140,0.0,0.0
9,Balaji,-1.0,20.0,6170,8160,Electronics and Electrical Engineering,1990,100.0,0.0
10,Rushitha,-1.0,62.0,7470,8090,Computer Science and Engineering,620,15.0,9.0
11,Balaraman Muthupandi,-1.0,0.0,7670,8050,Computer Science and Engineering,380,9.0,0.0
12,JPradhap,100.0,0.0,7340,8030,Electronics and Electrical Engineering,690,0.0,0.0
13,SRIRAMKUMAR B,-1.0,0.0,6400,7940,Computer Science and Engineering,1540,0.0,0.0
14,Praneetha,-1.0,100.0,7170,7730,Electronics and Communication Engineering,560,23.0,-1.0
15,Rahul Raj K,-1.0,0.0,6280,7640,Computer Science and Engineering,1360,0.0,0.0
16,Guhan S,-1.0,35.0,7310,7630,Electronics and Communication Engineering,320,72.0,39.0
17,Suryarajan S,-1.0,31.0,6710,7550,Computer Science and Engineering,840,63.0,0.0

In [31]:
Needs_Improvements.to_csv("/content/Needs_Improvement.csv",index=False)

###### if  codekate score < 7000        (Unsatisfactory.csv)

In [28]:
Unsatisfactory = df[(df['CodeKata Score']<7000)]
Unsatisfactory.reset_index(drop=True)

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,J.SUGANTHI,27.0,50.00,5860,5860,Electronics and Communication Engineering,0,NaN,NaN
1,thamizhpaana,29.0,0.00,5500,5500,Computer Science and Engineering,0,NaN,NaN
2,Iyappan Samiraj,50.0,24.00,5400,5400,Electronics and Communication Engineering,0,NaN,NaN
3,Ponniyamma.R,100.0,11.25,5380,5380,Computer Science and Engineering,0,NaN,NaN
4,SABAPATHI,100.0,0.00,5280,5280,Computer Science and Engineering,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
88,praveen raj j,24.0,0.00,2380,2380,Computer Science and Engineering,0,-1.0,0.0
89,AMARNATH D,-1.0,12.00,1890,1890,Electronics and Communication Engineering,0,52.0,-1.0
90,bala,32.0,0.00,1720,1720,Electronics and Communication Engineering,0,49.0,-1.0
91,XY Z,-1.0,-1.00,0,0,Computer Science and Engineering,0,20.0,-1.0
92,Hariharan,-1.0,-1.00,0,0,Computer Science and Engineering,0,-1.0,0.0

In [29]:
Unsatisfactory.to_csv("/content/Least.csv",index=False)

###### Average of previous week geekions vs this week geekions (i.e Previous Geekions vs CodeKata Score)

In [27]:
df['Previous Geekions'].mean(), df['CodeKata Score'].mean()

(3842.3529411764707, 4051.764705882353)

###### No of students participated

In [41]:
len(df['Name'].unique())

119

###### #Average completion of python course or my_sql or python english or computational thinking

In [42]:
print(df['python'].mean())
print(df['mysql'].mean())
print(df['python_en'].mean())
print(df['computational_thinking'].mean())

54.35294117647059
23.5
29.65714285714286
2.2

###### rising star of the week (top 3 candidate who performed well in that particular week)

In [45]:
df.sort_values('CodeKata Score',ascending=False)[:3]

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,A.Dharani,82.0,20.0,24500,24500,Computer Science and Engineering,0,NaN,NaN
1,V.JEEVITHA,82.0,20.0,21740,21740,Computer Science and Engineering,0,NaN,NaN
2,HEMAVATHI.R,100.0,100.0,19680,19680,Computer Science and Engineering,0,NaN,NaN

###### Shining stars of the week (top 3 candidates who has highest geekions)

In [48]:
df.sort_values('Previous Geekions',ascending=False)[:3]

,Name,python,mysql,Previous Geekions,CodeKata Score,Department,Rising,python_en,computational_thinking
0,A.Dharani,82.0,20.0,24500,24500,Computer Science and Engineering,0,NaN,NaN
1,V.JEEVITHA,82.0,20.0,21740,21740,Computer Science and Engineering,0,NaN,NaN
2,HEMAVATHI.R,100.0,100.0,19680,19680,Computer Science and Engineering,0,NaN,NaN

###### Department wise codekata performence (pie chart)

In [50]:
Pie_chart= px.pie(df,values='CodeKata Score',names='Department')
Pie_chart.show()

###### Department wise toppers (horizantal bar graph or any visual representations of your choice)

In [54]:
Dept_wise= df.sort_values('CodeKata Score',ascending=True)
Dept_wise_visual = px.bar(Dept_wise,'Department','CodeKata Score',color='Previous Geekions',hover_name='Name')
Dept_wise_visual.show()